name: EuclidPolishEnv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - tensorflow
  - numpy
  - pandas
  - tensorflow-probability
  - matplotlib
  - opencv
  - scipy
  - astropy
  - scikit-image
  - tf-keras
  - tqdm
  - astroquery
  - photutils
  - questionary
  - pytest
  - flask
  - pip
  - pip:
      - lenstronomy
